name: Set up Node.js and Yarn
description: Use Volta to set up pinned versions of Node.js and Yarn. Cache the Yarn cache directory.
author: LayZeeDK

runs:
  using: composite
  steps:
    - name: Set up Node.js and Yarn
      uses: volta-cli/action@v4
    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - name: Get Node.js version
      id: node-version
      shell: bash
      run: echo "version=$(node -v)" >> $GITHUB_OUTPUT
    - name: Cache Yarn cache directory
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ steps.node-version.outputs.version }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.node-version.outputs.version }}-yarn-
