name: CI

concurrency:
  group: ci@${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

env:
  is-main-branch: ${{ github.ref_name == 'main' }}
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  validate-renovate:
    name: 'Validate Renovate configuration @await'
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js LTS
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: lts/*
      - name: Install Renovate
        run: npm install --global renovate

      - name: Validate Renovate configuration
        run: renovate-config-validator

  lint:
    name: 'Lint @await'
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Lint
        run: yarn lint
  test:
    name: 'Test @await'
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Test
        run: yarn test

  build:
    name: 'Build @await'
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Build
        run: yarn build

      - name: 'Merge: Upload package bundle'
        if: ${{ env.is-main-branch == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: ngworker-router-component-store
          path: dist/packages/router-component-store
