name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group on branch name (`refs/heads/main`)
  # - Is pull request? Group on pull request branch name, for example `feat/add-awesome-feature`
  group: >-
    ${{ github.workflow }}-${{
      github.event_name == 'push'
        && github.ref
        || github.head_ref
    }}
  # Run merge workflows in sequence to prevent parallel deployments and releases
  # Cancel stale pull request runs in progress for the same branch
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  is-merge-to-main: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Build
        run: yarn build
      - name: Bundle readme
        run: cp README.md dist/packages/router-component-store/

      - name: '[Merge] Upload package bundle'
        if: ${{ env.is-merge-to-main == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: ngworker-router-component-store
          path: dist/packages/router-component-store
          if-no-files-found: error
          retention-days: 7
