name: CI

concurrency:
  group: ci@${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  is-main-branch: ${{ github.ref_name == 'main' }}
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Set up Node.js and install dependencies
        uses: ./.github/actions/setup-node
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --no-interactive

      - name: Build
        run: yarn build

      - name: 'Merge: Upload package bundle'
        if: ${{ env.is-main-branch == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: ngworker-router-component-store
          path: dist/packages/router-component-store
