name: CI

concurrency:
  group: ci@${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

env:
  is-main-branch: ${{ github.ref_name == 'main' }}
  node-version: 14.x
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  validate-renovate:
    name: Validate Renovate configuration
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - name: Install Renovate
        run: npm install --global renovate

      - name: Validate Renovate configuration
        run: renovate-config-validator

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install package dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install package dependencies
        run: yarn install

      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install package dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: 'Merge: Upload package bundle'
        if: ${{ env.is-main-branch == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: ngworker-router-component-store
          path: dist/packages/router-component-store
