name: Migrate Nx workspace

concurrency:
  group: nx-migrate@${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

on:
  push:
    branches:
      - renovate/nx-migrate
  workflow_dispatch:
    branches:
      - renovate/nx-migrate

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  migrate:
    name: Migrate Nx workspace
    if: ${{ github.event_name == 'workflow_dispatch' || contains(fromJSON('["bot@renovateapp.com", "29139614+renovate[bot]@users.noreply.github.com"]'), github.event.head_commit.author.email) }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - name: Fetch base branch
        run: git fetch origin main --depth=1
      - name: Check out base branch
        run: git switch main
      - name: Check out head branch
        run: git checkout -

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version-file: .nvmrc
      - name: Install package dependencies
        run: yarn install

      - name: Migrate Nx workspace
        run: yarn nx run tools:migrate-nx

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "feat(deps): migrate Nx-managed dependencies"
          git push
